### ISSUE TITLE
[hg_uv98] in Settings tab I can see only the first two options (Basic and Display)

### ISSUE THREAD

**Issue by masenf** [masenf/chirp#1]
Reported from [groups.io post](https://groups.io/g/HG-UV98-users/message/375).

Stack trace from debug log is

```
Traceback (most recent call last):
  File "chirp\ui\settingsedit.pyo", line 225, in _build_ui
  File "chirp\ui\settingsedit.pyo", line 209, in _build_ui_group
  File "chirp\ui\settingsedit.pyo", line 183, in _build_ui_tab
TypeError: Gtk.ComboBox.append_text() argument 1 must be string without null bytes, not str
[2022-11-11 05:59:42,461] chirp.ui.editorset - DEBUG: <RadioBrowser object at 0x42456c0 (chirp+ui+common+Editor at 0x526b560)> changed
```

**Comment by bazie0** [comment]
[BZ_HG-UV98.zip](https://github.com/masenf/chirp/files/9986667/BZ_HG-UV98.zip)
I attach a ZIP with debug.log and HG-UV98 config.
Interesting, using the driver I was testing in April, I get all the fields displayed.
The stock config displays properly.
