### ISSUE TITLE
[hg_uv98] Cannot clone from radio using CHIRP next-20240217 regardless of OS

### ISSUE THREAD

**Issue by klaeufer** [masenf/chirp#3]
I tried cloning from radio using CHIRP next-20240217 on MacOS 14.3.1 as well as a Windows VM, using a FTDI cable and the included cable. The result is the same:

Chirp shows progress to completion as it is cloning from radio. Then nothing happens other than the radio rebooting and the unsuccessful download being stored in the backup folder:

-rw-r--r--  1 laufer  staff  8369 Feb 17 13:50 Lanchonlh_HG-UV98_20240217T135045.img

The log shows many DEBUG messages during the download itself and ends with this traceback:

```
[2024-02-17 13:50:45,859] chirp.wxui.main - INFO: Saved backup to /Users/laufer/.chirp/backups/Lanchonlh_HG-UV98_20240217T135045.img
Traceback (most recent call last):
  File "chirp/wxui/main.py", line 1517, in _menu_download
  File "chirp/wxui/main.py", line 205, in __init__
  File "chirp/wxui/memedit.py", line 1161, in refresh
  File "chirp/wxui/memedit.py", line 1067, in refresh_memory
  File "chirp/wxui/common.py", line 290, in do_radio
  File "chirp/wxui/memedit.py", line 1063, in get_cb
  File "chirp/wxui/common.py", line 290, in do_radio
  File "chirp/wxui/memedit.py", line 1046, in extra_cb
  File "chirp/wxui/memedit.py", line 958, in _refresh_memory
  File "chirp/wxui/memedit.py", line 918, in mem2row
KeyError: 'A'
```

I also get a corresponding popup when trying to open the backup file manually:

```
An error has occurred

'A'
```

**Comment by klaeufer** [comment]
I just noticed that your driver has been merged into the main repo.

**Comment by masenf** [comment]
@klaeufer definitely let me know if you still have issues with the driver on mainline. I don't check in with the chirp bug tracker as much as I should.

**Comment by klaeufer** [comment]
Thanks, @masenf, for your prompt response. I just figured out that I had to create a Chirp-specific account to report the issue on Redmine.
